Repository NoDesk-6BD/6sem2025Main, pull requests merged in 2025-09, with the labels that each got.

#3 Fix (ND-19): Atualizando documentação
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  documentation/images/equipe-nodesk-sem-fundo.png
  documentation/images/equipe-nodesk.jpg
  documentation/images/logo-nodesk.png
Labels: documentation, enhancement

#4 Feature (ND-20): Definição e implementação do pre-commit
  .gitignore
  .pre-commit-config.yaml
  documentation/fluxo-git/pre-commit.md
  documentation/images/pre-commit-code-errors.png
  documentation/images/pre-commit-install-active.png
  documentation/images/pre-commit-non-standard.png
  documentation/images/pre-commit-standard-success.png
Labels: enhancement

#6 Fix (ND-40) Adjusting documents and readme to english
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
  documentation/fluxo-git/padrao-branch-commit.md
  documentation/fluxo-git/pre-commit.md
  documentation/fluxo-git/pull-request.md
  documentation/git-flow/branch-commit-pattern.md
  documentation/git-flow/pre-commit.md
  documentation/git-flow/pull-request-pattern.md
Labels: documentation, enhancement

#7 Sprint-1 to Main
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  .pre-commit-config.yaml
  README.md
  documentation/git-flow/branch-commit-pattern.md
  documentation/git-flow/pre-commit.md
  documentation/git-flow/pull-request-pattern.md
  documentation/images/equipe-nodesk-sem-fundo.png
  documentation/images/equipe-nodesk.jpg
  documentation/images/logo-nodesk.png
  documentation/images/pre-commit-code-errors.png
  documentation/images/pre-commit-install-active.png
  documentation/images/pre-commit-non-standard.png
  documentation/images/pre-commit-standard-success.png
Labels: enhancement

#10 Doc (ND-35): Adding figma to README
  README.md
Labels: documentation
